# Wrangler configuration for Cloudflare Pages
name = "dingzz-marketing"
compatibility_date = "2023-06-02"
pages_build_output_dir = "dist"

# Configure environment variables
[vars]
NODE_VERSION = "20"
SWC_USE_WASM = "1"
